/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AuditEventList } from '../models';
/**
 * AuditApi - axios parameter creator
 */
export const AuditApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List audit events
         * @param {number} [limit] 
         * @param {string} [cursor] Reserved for future pagination
         * @param {string} [action] Filter by action name
         * @param {string} [actorId] Filter by actor id
         * @param {string} [targetType] Filter by target type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAuditEvents: async (limit?: number, cursor?: string, action?: string, actorId?: string, targetType?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/audit-events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (action !== undefined) {
                localVarQueryParameter['action'] = action;
            }

            if (actorId !== undefined) {
                localVarQueryParameter['actorId'] = actorId;
            }

            if (targetType !== undefined) {
                localVarQueryParameter['targetType'] = targetType;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuditApi - functional programming interface
 */
export const AuditApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuditApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List audit events
         * @param {number} [limit] 
         * @param {string} [cursor] Reserved for future pagination
         * @param {string} [action] Filter by action name
         * @param {string} [actorId] Filter by actor id
         * @param {string} [targetType] Filter by target type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAuditEvents(limit?: number, cursor?: string, action?: string, actorId?: string, targetType?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuditEventList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listAuditEvents(limit, cursor, action, actorId, targetType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuditApi.listAuditEvents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuditApi - factory interface
 */
export const AuditApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuditApiFp(configuration)
    return {
        /**
         * 
         * @summary List audit events
         * @param {number} [limit] 
         * @param {string} [cursor] Reserved for future pagination
         * @param {string} [action] Filter by action name
         * @param {string} [actorId] Filter by actor id
         * @param {string} [targetType] Filter by target type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAuditEvents(limit?: number, cursor?: string, action?: string, actorId?: string, targetType?: string, options?: RawAxiosRequestConfig): AxiosPromise<AuditEventList> {
            return localVarFp.listAuditEvents(limit, cursor, action, actorId, targetType, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuditApi - object-oriented interface
 */
export class AuditApi extends BaseAPI {
    /**
     * 
     * @summary List audit events
     * @param {number} [limit] 
     * @param {string} [cursor] Reserved for future pagination
     * @param {string} [action] Filter by action name
     * @param {string} [actorId] Filter by actor id
     * @param {string} [targetType] Filter by target type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listAuditEvents(limit?: number, cursor?: string, action?: string, actorId?: string, targetType?: string, options?: RawAxiosRequestConfig) {
        return AuditApiFp(this.configuration).listAuditEvents(limit, cursor, action, actorId, targetType, options).then((request) => request(this.axios, this.basePath));
    }
}

