/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * EventsApi - axios parameter creator
 */
export const EventsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Global Server-Sent Events stream (firehose; no query parameters)
         * @param {string} clientSessionId Frontend-generated session identifier (UUID) used to route SSE events.
         * @param {string} [lastEventID] Resume SSE from a specific monotonic event id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sseGlobalEvents: async (clientSessionId: string, lastEventID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientSessionId' is not null or undefined
            assertParamExists('sseGlobalEvents', 'clientSessionId', clientSessionId)
            const localVarPath = `/api/v1/events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (clientSessionId !== undefined) {
                localVarQueryParameter['clientSessionId'] = clientSessionId;
            }


    
            if (lastEventID != null) {
                localVarHeaderParameter['Last-Event-ID'] = String(lastEventID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EventsApi - functional programming interface
 */
export const EventsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EventsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Global Server-Sent Events stream (firehose; no query parameters)
         * @param {string} clientSessionId Frontend-generated session identifier (UUID) used to route SSE events.
         * @param {string} [lastEventID] Resume SSE from a specific monotonic event id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sseGlobalEvents(clientSessionId: string, lastEventID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sseGlobalEvents(clientSessionId, lastEventID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventsApi.sseGlobalEvents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EventsApi - factory interface
 */
export const EventsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EventsApiFp(configuration)
    return {
        /**
         * 
         * @summary Global Server-Sent Events stream (firehose; no query parameters)
         * @param {string} clientSessionId Frontend-generated session identifier (UUID) used to route SSE events.
         * @param {string} [lastEventID] Resume SSE from a specific monotonic event id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sseGlobalEvents(clientSessionId: string, lastEventID?: string, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.sseGlobalEvents(clientSessionId, lastEventID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EventsApi - object-oriented interface
 */
export class EventsApi extends BaseAPI {
    /**
     * 
     * @summary Global Server-Sent Events stream (firehose; no query parameters)
     * @param {string} clientSessionId Frontend-generated session identifier (UUID) used to route SSE events.
     * @param {string} [lastEventID] Resume SSE from a specific monotonic event id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sseGlobalEvents(clientSessionId: string, lastEventID?: string, options?: RawAxiosRequestConfig) {
        return EventsApiFp(this.configuration).sseGlobalEvents(clientSessionId, lastEventID, options).then((request) => request(this.axios, this.basePath));
    }
}

