/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { RegistryAccountLink } from '../models';
// @ts-ignore
import type { RegistryAccountLinkRequest } from '../models';
// @ts-ignore
import type { RegistryWorkflowImportRequest } from '../models';
// @ts-ignore
import type { RegistryWorkflowImportResponse } from '../models';
/**
 * RegistryApi - axios parameter creator
 */
export const RegistryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get linked registry account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRegistryAccount: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/registry/account`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Import a registry workflow into the platform
         * @param {RegistryWorkflowImportRequest} registryWorkflowImportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        importRegistryWorkflow: async (registryWorkflowImportRequest: RegistryWorkflowImportRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registryWorkflowImportRequest' is not null or undefined
            assertParamExists('importRegistryWorkflow', 'registryWorkflowImportRequest', registryWorkflowImportRequest)
            const localVarPath = `/api/v1/registry/workflows/import`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registryWorkflowImportRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Link registry account
         * @param {RegistryAccountLinkRequest} registryAccountLinkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        linkRegistryAccount: async (registryAccountLinkRequest: RegistryAccountLinkRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registryAccountLinkRequest' is not null or undefined
            assertParamExists('linkRegistryAccount', 'registryAccountLinkRequest', registryAccountLinkRequest)
            const localVarPath = `/api/v1/registry/account`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registryAccountLinkRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Unlink registry account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unlinkRegistryAccount: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/registry/account`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RegistryApi - functional programming interface
 */
export const RegistryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RegistryApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get linked registry account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRegistryAccount(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegistryAccountLink>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRegistryAccount(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegistryApi.getRegistryAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Import a registry workflow into the platform
         * @param {RegistryWorkflowImportRequest} registryWorkflowImportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async importRegistryWorkflow(registryWorkflowImportRequest: RegistryWorkflowImportRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegistryWorkflowImportResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.importRegistryWorkflow(registryWorkflowImportRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegistryApi.importRegistryWorkflow']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Link registry account
         * @param {RegistryAccountLinkRequest} registryAccountLinkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async linkRegistryAccount(registryAccountLinkRequest: RegistryAccountLinkRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegistryAccountLink>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.linkRegistryAccount(registryAccountLinkRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegistryApi.linkRegistryAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Unlink registry account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unlinkRegistryAccount(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unlinkRegistryAccount(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegistryApi.unlinkRegistryAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RegistryApi - factory interface
 */
export const RegistryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RegistryApiFp(configuration)
    return {
        /**
         * 
         * @summary Get linked registry account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRegistryAccount(options?: RawAxiosRequestConfig): AxiosPromise<RegistryAccountLink> {
            return localVarFp.getRegistryAccount(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Import a registry workflow into the platform
         * @param {RegistryWorkflowImportRequest} registryWorkflowImportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        importRegistryWorkflow(registryWorkflowImportRequest: RegistryWorkflowImportRequest, options?: RawAxiosRequestConfig): AxiosPromise<RegistryWorkflowImportResponse> {
            return localVarFp.importRegistryWorkflow(registryWorkflowImportRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Link registry account
         * @param {RegistryAccountLinkRequest} registryAccountLinkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        linkRegistryAccount(registryAccountLinkRequest: RegistryAccountLinkRequest, options?: RawAxiosRequestConfig): AxiosPromise<RegistryAccountLink> {
            return localVarFp.linkRegistryAccount(registryAccountLinkRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Unlink registry account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unlinkRegistryAccount(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.unlinkRegistryAccount(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RegistryApi - object-oriented interface
 */
export class RegistryApi extends BaseAPI {
    /**
     * 
     * @summary Get linked registry account
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRegistryAccount(options?: RawAxiosRequestConfig) {
        return RegistryApiFp(this.configuration).getRegistryAccount(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Import a registry workflow into the platform
     * @param {RegistryWorkflowImportRequest} registryWorkflowImportRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public importRegistryWorkflow(registryWorkflowImportRequest: RegistryWorkflowImportRequest, options?: RawAxiosRequestConfig) {
        return RegistryApiFp(this.configuration).importRegistryWorkflow(registryWorkflowImportRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Link registry account
     * @param {RegistryAccountLinkRequest} registryAccountLinkRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public linkRegistryAccount(registryAccountLinkRequest: RegistryAccountLinkRequest, options?: RawAxiosRequestConfig) {
        return RegistryApiFp(this.configuration).linkRegistryAccount(registryAccountLinkRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Unlink registry account
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public unlinkRegistryAccount(options?: RawAxiosRequestConfig) {
        return RegistryApiFp(this.configuration).unlinkRegistryAccount(options).then((request) => request(this.axios, this.basePath));
    }
}

