/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Workflow } from '../models';
// @ts-ignore
import type { WorkflowPackageCloneRequest } from '../models';
// @ts-ignore
import type { WorkflowPackageDetail } from '../models';
// @ts-ignore
import type { WorkflowPackageList } from '../models';
// @ts-ignore
import type { WorkflowPackageVersionList } from '../models';
// @ts-ignore
import type { WorkflowPublishRequest } from '../models';
// @ts-ignore
import type { WorkflowPublishResponse } from '../models';
// @ts-ignore
import type { WorkflowRef } from '../models';
/**
 * WorkflowPackagesApi - axios parameter creator
 */
export const WorkflowPackagesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Clone a workflow package version into the caller\'s workspace
         * @param {string} packageId 
         * @param {WorkflowPackageCloneRequest} [workflowPackageCloneRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloneWorkflowPackage: async (packageId: string, workflowPackageCloneRequest?: WorkflowPackageCloneRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'packageId' is not null or undefined
            assertParamExists('cloneWorkflowPackage', 'packageId', packageId)
            const localVarPath = `/api/v1/workflow-packages/{packageId}/clone`
                .replace(`{${"packageId"}}`, encodeURIComponent(String(packageId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(workflowPackageCloneRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a workflow package
         * @param {string} packageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWorkflowPackage: async (packageId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'packageId' is not null or undefined
            assertParamExists('deleteWorkflowPackage', 'packageId', packageId)
            const localVarPath = `/api/v1/workflow-packages/{packageId}`
                .replace(`{${"packageId"}}`, encodeURIComponent(String(packageId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a workflow package detail
         * @param {string} packageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWorkflowPackage: async (packageId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'packageId' is not null or undefined
            assertParamExists('getWorkflowPackage', 'packageId', packageId)
            const localVarPath = `/api/v1/workflow-packages/{packageId}`
                .replace(`{${"packageId"}}`, encodeURIComponent(String(packageId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a workflow package definition snapshot
         * @param {string} packageId 
         * @param {string} versionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWorkflowPackageDefinition: async (packageId: string, versionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'packageId' is not null or undefined
            assertParamExists('getWorkflowPackageDefinition', 'packageId', packageId)
            // verify required parameter 'versionId' is not null or undefined
            assertParamExists('getWorkflowPackageDefinition', 'versionId', versionId)
            const localVarPath = `/api/v1/workflow-packages/{packageId}/versions/{versionId}/definition`
                .replace(`{${"packageId"}}`, encodeURIComponent(String(packageId)))
                .replace(`{${"versionId"}}`, encodeURIComponent(String(versionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List versions for a workflow package
         * @param {string} packageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listWorkflowPackageVersions: async (packageId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'packageId' is not null or undefined
            assertParamExists('listWorkflowPackageVersions', 'packageId', packageId)
            const localVarPath = `/api/v1/workflow-packages/{packageId}/versions`
                .replace(`{${"packageId"}}`, encodeURIComponent(String(packageId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List published workflow packages
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {string} [owner] Filter by owner id; use &#x60;me&#x60; for the caller\&#39;s id.
         * @param {string} [visibility] Filter by visibility (private, internal, public).
         * @param {string} [search] Full-text search across slug, display name, and summary.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listWorkflowPackages: async (limit?: number, cursor?: string, owner?: string, visibility?: string, search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/workflow-packages`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (owner !== undefined) {
                localVarQueryParameter['owner'] = owner;
            }

            if (visibility !== undefined) {
                localVarQueryParameter['visibility'] = visibility;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Publish a workflow draft to the Store
         * @param {string} workflowId 
         * @param {WorkflowPublishRequest} workflowPublishRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publishWorkflow: async (workflowId: string, workflowPublishRequest: WorkflowPublishRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workflowId' is not null or undefined
            assertParamExists('publishWorkflow', 'workflowId', workflowId)
            // verify required parameter 'workflowPublishRequest' is not null or undefined
            assertParamExists('publishWorkflow', 'workflowPublishRequest', workflowPublishRequest)
            const localVarPath = `/api/v1/workflows/{workflowId}/publish`
                .replace(`{${"workflowId"}}`, encodeURIComponent(String(workflowId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(workflowPublishRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WorkflowPackagesApi - functional programming interface
 */
export const WorkflowPackagesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WorkflowPackagesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Clone a workflow package version into the caller\'s workspace
         * @param {string} packageId 
         * @param {WorkflowPackageCloneRequest} [workflowPackageCloneRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloneWorkflowPackage(packageId: string, workflowPackageCloneRequest?: WorkflowPackageCloneRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowRef>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloneWorkflowPackage(packageId, workflowPackageCloneRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowPackagesApi.cloneWorkflowPackage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a workflow package
         * @param {string} packageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteWorkflowPackage(packageId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteWorkflowPackage(packageId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowPackagesApi.deleteWorkflowPackage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a workflow package detail
         * @param {string} packageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWorkflowPackage(packageId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowPackageDetail>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWorkflowPackage(packageId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowPackagesApi.getWorkflowPackage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a workflow package definition snapshot
         * @param {string} packageId 
         * @param {string} versionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWorkflowPackageDefinition(packageId: string, versionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Workflow>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWorkflowPackageDefinition(packageId, versionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowPackagesApi.getWorkflowPackageDefinition']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List versions for a workflow package
         * @param {string} packageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listWorkflowPackageVersions(packageId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowPackageVersionList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listWorkflowPackageVersions(packageId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowPackagesApi.listWorkflowPackageVersions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List published workflow packages
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {string} [owner] Filter by owner id; use &#x60;me&#x60; for the caller\&#39;s id.
         * @param {string} [visibility] Filter by visibility (private, internal, public).
         * @param {string} [search] Full-text search across slug, display name, and summary.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listWorkflowPackages(limit?: number, cursor?: string, owner?: string, visibility?: string, search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowPackageList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listWorkflowPackages(limit, cursor, owner, visibility, search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowPackagesApi.listWorkflowPackages']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Publish a workflow draft to the Store
         * @param {string} workflowId 
         * @param {WorkflowPublishRequest} workflowPublishRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async publishWorkflow(workflowId: string, workflowPublishRequest: WorkflowPublishRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowPublishResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.publishWorkflow(workflowId, workflowPublishRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowPackagesApi.publishWorkflow']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WorkflowPackagesApi - factory interface
 */
export const WorkflowPackagesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WorkflowPackagesApiFp(configuration)
    return {
        /**
         * 
         * @summary Clone a workflow package version into the caller\'s workspace
         * @param {string} packageId 
         * @param {WorkflowPackageCloneRequest} [workflowPackageCloneRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloneWorkflowPackage(packageId: string, workflowPackageCloneRequest?: WorkflowPackageCloneRequest, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowRef> {
            return localVarFp.cloneWorkflowPackage(packageId, workflowPackageCloneRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a workflow package
         * @param {string} packageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWorkflowPackage(packageId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteWorkflowPackage(packageId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a workflow package detail
         * @param {string} packageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWorkflowPackage(packageId: string, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowPackageDetail> {
            return localVarFp.getWorkflowPackage(packageId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a workflow package definition snapshot
         * @param {string} packageId 
         * @param {string} versionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWorkflowPackageDefinition(packageId: string, versionId: string, options?: RawAxiosRequestConfig): AxiosPromise<Workflow> {
            return localVarFp.getWorkflowPackageDefinition(packageId, versionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List versions for a workflow package
         * @param {string} packageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listWorkflowPackageVersions(packageId: string, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowPackageVersionList> {
            return localVarFp.listWorkflowPackageVersions(packageId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List published workflow packages
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {string} [owner] Filter by owner id; use &#x60;me&#x60; for the caller\&#39;s id.
         * @param {string} [visibility] Filter by visibility (private, internal, public).
         * @param {string} [search] Full-text search across slug, display name, and summary.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listWorkflowPackages(limit?: number, cursor?: string, owner?: string, visibility?: string, search?: string, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowPackageList> {
            return localVarFp.listWorkflowPackages(limit, cursor, owner, visibility, search, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Publish a workflow draft to the Store
         * @param {string} workflowId 
         * @param {WorkflowPublishRequest} workflowPublishRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publishWorkflow(workflowId: string, workflowPublishRequest: WorkflowPublishRequest, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowPublishResponse> {
            return localVarFp.publishWorkflow(workflowId, workflowPublishRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WorkflowPackagesApi - object-oriented interface
 */
export class WorkflowPackagesApi extends BaseAPI {
    /**
     * 
     * @summary Clone a workflow package version into the caller\'s workspace
     * @param {string} packageId 
     * @param {WorkflowPackageCloneRequest} [workflowPackageCloneRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cloneWorkflowPackage(packageId: string, workflowPackageCloneRequest?: WorkflowPackageCloneRequest, options?: RawAxiosRequestConfig) {
        return WorkflowPackagesApiFp(this.configuration).cloneWorkflowPackage(packageId, workflowPackageCloneRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a workflow package
     * @param {string} packageId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteWorkflowPackage(packageId: string, options?: RawAxiosRequestConfig) {
        return WorkflowPackagesApiFp(this.configuration).deleteWorkflowPackage(packageId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a workflow package detail
     * @param {string} packageId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getWorkflowPackage(packageId: string, options?: RawAxiosRequestConfig) {
        return WorkflowPackagesApiFp(this.configuration).getWorkflowPackage(packageId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a workflow package definition snapshot
     * @param {string} packageId 
     * @param {string} versionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getWorkflowPackageDefinition(packageId: string, versionId: string, options?: RawAxiosRequestConfig) {
        return WorkflowPackagesApiFp(this.configuration).getWorkflowPackageDefinition(packageId, versionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List versions for a workflow package
     * @param {string} packageId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listWorkflowPackageVersions(packageId: string, options?: RawAxiosRequestConfig) {
        return WorkflowPackagesApiFp(this.configuration).listWorkflowPackageVersions(packageId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List published workflow packages
     * @param {number} [limit] 
     * @param {string} [cursor] 
     * @param {string} [owner] Filter by owner id; use &#x60;me&#x60; for the caller\&#39;s id.
     * @param {string} [visibility] Filter by visibility (private, internal, public).
     * @param {string} [search] Full-text search across slug, display name, and summary.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listWorkflowPackages(limit?: number, cursor?: string, owner?: string, visibility?: string, search?: string, options?: RawAxiosRequestConfig) {
        return WorkflowPackagesApiFp(this.configuration).listWorkflowPackages(limit, cursor, owner, visibility, search, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Publish a workflow draft to the Store
     * @param {string} workflowId 
     * @param {WorkflowPublishRequest} workflowPublishRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public publishWorkflow(workflowId: string, workflowPublishRequest: WorkflowPublishRequest, options?: RawAxiosRequestConfig) {
        return WorkflowPackagesApiFp(this.configuration).publishWorkflow(workflowId, workflowPublishRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

