/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */
import type { AuthLoginResponseTokenType } from './authLoginResponseTokenType';
import type { UserSummary } from './userSummary';

export interface AuthLoginResponse {
  accessToken: string;
  tokenType: AuthLoginResponseTokenType;
  /** Seconds until the access token expires. */
  expiresIn: number;
  user: UserSummary;
}
