/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */
import type { Error } from './error';

/**
 * Invalid input
 */
export type BadRequestResponse = Error;
