/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */
import type { BindingScopeKind } from './bindingScopeKind';

/**
 * Canonical representation of a binding prefix used to resolve nodes across workflows or subgraphs.
 */
export interface BindingScope {
  /** local = default workflow, subgraph = inline subgraph alias chain. */
  kind?: BindingScopeKind;
  /** Ordered list of inline subgraph aliases traversed to reach the node. */
  subgraphAliases?: string[];
  /** Explicit node identifier within the resolved scope (used for '#nodeId' prefixes or workflow-level references). */
  nodeId?: string;
  /** Raw prefix string captured before parsing (mirrors UIBinding.prefix for auditing/backwards compatibility). */
  prefix?: string;
}
