/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */
import type { CatalogNodeVersion } from './catalogNodeVersion';

export interface CatalogNode {
  type: string;
  label: string;
  description?: string;
  role?: string;
  category?: string;
  tags?: string[];
  status?: string;
  packageName: string;
  defaultVersion?: string;
  latestVersion?: string;
  versions: CatalogNodeVersion[];
}
