/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */
import type { ManifestNode } from './manifestNode';

export interface CatalogNodeVersion {
  version: string;
  /** Optional status reported by the worker for this version. */
  status?: string;
  template?: ManifestNode;
}
