/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */
import type { TraceContext } from './traceContext';
import type { CmdDispatchPayload } from './cmdDispatchPayload';

export interface CmdDispatch {
  kind: 'cmd.dispatch';
  runId: string;
  nodeId: string;
  definitionHash: string;
  trace: TraceContext;
  payload?: CmdDispatchPayload;
}
