/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

export interface CommandAck {
  kind?: 'command.ack';
  commandId?: string;
  workerId?: string;
  receivedAt?: string;
}
