/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

/**
 * Optional idempotency key for safe retries; if reused with a different body, return 409
 */
export type IdempotencyKeyParameter = string;
