/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

export type ListAuditEventsParams = {
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * Reserved for future pagination
 */
cursor?: string;
/**
 * Filter by action name
 */
action?: string;
/**
 * Filter by actor id
 */
actorId?: string;
/**
 * Filter by target type
 */
targetType?: string;
};
