/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */
import type { PageLimit } from './pageLimit';
import type { PageCursor } from './pageCursor';
import type { RunStatus } from './runStatus';

export type ListRunsParams = {
/**
 * @minimum 1
 * @maximum 200
 */
limit?: PageLimit;
cursor?: PageCursor;
status?: RunStatus;
clientId?: string;
};
