/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

export interface ManifestResource {
  path: string;
  type: string;
  /** @pattern ^[A-Fa-f0-9]{64}$ */
  sha256?: string;
}
