/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

export type ManifestNodeStatus = typeof ManifestNodeStatus[keyof typeof ManifestNodeStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ManifestNodeStatus = {
  draft: 'draft',
  published: 'published',
  deprecated: 'deprecated',
} as const;
