/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */
import type { ManifestAdapterMetadata } from './manifestAdapterMetadata';

export interface ManifestAdapter {
  name: string;
  /** @pattern ^[A-Za-z_][A-Za-z0-9_.]*:[A-Za-z_][A-Za-z0-9_.]*$ */
  entrypoint: string;
  /** @minItems 1 */
  capabilities: string[];
  description?: string;
  idempotency?: string;
  metadata?: ManifestAdapterMetadata;
}
