/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */
import type { ManifestNodeRole } from './manifestNodeRole';
import type { ManifestNodeStatus } from './manifestNodeStatus';
import type { ManifestNodeConfig } from './manifestNodeConfig';
import type { ManifestNodeSchema } from './manifestNodeSchema';
import type { ManifestNodeUI } from './manifestNodeUI';

export interface ManifestNode {
  /** @pattern ^[A-Za-z0-9_.-]+$ */
  type: string;
  /** Execution role of the node. */
  role?: ManifestNodeRole;
  status: ManifestNodeStatus;
  category: string;
  label: string;
  description?: string;
  tags?: string[];
  /** @pattern ^[A-Za-z0-9_.-]+$ */
  adapter: string;
  /** @pattern ^[A-Za-z_][A-Za-z0-9_]*$ */
  handler: string;
  /** Optional static configuration forwarded to the handler. */
  config?: ManifestNodeConfig;
  schema: ManifestNodeSchema;
  ui?: ManifestNodeUI;
}
