/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

export type ManifestBindingMode = typeof ManifestBindingMode[keyof typeof ManifestBindingMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ManifestBindingMode = {
  read: 'read',
  write: 'write',
  two_way: 'two_way',
} as const;
