/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

export type NodeResultDeltaEventOperation = typeof NodeResultDeltaEventOperation[keyof typeof NodeResultDeltaEventOperation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NodeResultDeltaEventOperation = {
  append: 'append',
  replace: 'replace',
  patch: 'patch',
} as const;
