/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */
import type { WorkflowNodeState } from './workflowNodeState';

export interface NodeStateEvent {
  kind: 'node.state';
  runId: string;
  nodeId: string;
  state: WorkflowNodeState;
}
