/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

export interface PackageSummary {
  name: string;
  description?: string;
  latestVersion?: string;
  defaultVersion?: string;
  versions: string[];
}
