/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

export type SearchCatalogNodesParams = {
/**
 * Search text applied to node name, type, description, and tags.
 */
q: string;
/**
 * Optional package filter derived from search results.
 */
package?: string;
};
