/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */
import type { RunStatusEvent } from './runStatusEvent';
import type { RunSnapshotEvent } from './runSnapshotEvent';
import type { RunMetricsEvent } from './runMetricsEvent';
import type { NodeStateEvent } from './nodeStateEvent';
import type { NodeStatusEvent } from './nodeStatusEvent';
import type { NodeResultSnapshotEvent } from './nodeResultSnapshotEvent';
import type { NodeResultDeltaEvent } from './nodeResultDeltaEvent';
import type { NodeErrorEvent } from './nodeErrorEvent';
import type { ArtifactEvent } from './artifactEvent';
import type { CommandAckEvent } from './commandAckEvent';
import type { CommandErrorEvent } from './commandErrorEvent';
import type { WorkerHeartbeatEvent } from './workerHeartbeatEvent';
import type { WorkerPackageSseEvent } from './workerPackageSseEvent';

export type UiEventPayload = RunStatusEvent | RunSnapshotEvent | RunMetricsEvent | NodeStateEvent | NodeStatusEvent | NodeResultSnapshotEvent | NodeResultDeltaEvent | NodeErrorEvent | ArtifactEvent | CommandAckEvent | CommandErrorEvent | WorkerHeartbeatEvent | WorkerPackageSseEvent;
