/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

export interface UiEventScope {
  tenant: string;
  /** @nullable */
  runId?: string | null;
  /** @nullable */
  workerId?: string | null;
  /** @nullable */
  clientSessionId?: string | null;
  /** @nullable */
  clientInstanceId?: string | null;
}
