/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

/**
 * Middleware lifecycle state.
 */
export type WorkflowMiddlewareStatus = typeof WorkflowMiddlewareStatus[keyof typeof WorkflowMiddlewareStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkflowMiddlewareStatus = {
  draft: 'draft',
  published: 'published',
  deprecated: 'deprecated',
} as const;
