/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

export interface WorkflowSubgraphMetadata {
  /** Optional human-friendly label for the subgraph. */
  label?: string;
  description?: string;
  /** Original workflow id when this subgraph was created from a reference. */
  referenceWorkflowId?: string;
  referenceWorkflowName?: string;
  ownerId?: string;
  notes?: string;
}
