/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

export type WorkerPackageSseEventStatus = typeof WorkerPackageSseEventStatus[keyof typeof WorkerPackageSseEventStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkerPackageSseEventStatus = {
  installing: 'installing',
  installed: 'installed',
  removing: 'removing',
  removed: 'removed',
  failed: 'failed',
} as const;
