/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */
import type { WorkflowPackageVersion } from './workflowPackageVersion';

export interface WorkflowPackageSummary {
  id: string;
  slug: string;
  displayName: string;
  /** @nullable */
  summary?: string | null;
  /** Visibility policy (private/internal/public). */
  visibility: string;
  /** @nullable */
  tags?: string[] | null;
  /** @nullable */
  ownerId?: string | null;
  /** @nullable */
  ownerName?: string | null;
  /** @nullable */
  updatedAt?: string | null;
  latestVersion?: WorkflowPackageVersion;
  /**
   * Base64-encoded preview from the latest version when available.
   * @nullable
   */
  previewImage?: string | null;
}
