/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */
import type { WorkflowMetadata } from './workflowMetadata';
import type { WorkflowNode } from './workflowNode';
import type { WorkflowEdge } from './workflowEdge';

export interface Workflow {
  /** Workflow UUID */
  id: string;
  /**
   * e.g. "2025-10"
   * @pattern ^[0-9]{4}-[0-9]{2}$
   */
  schemaVersion: string;
  metadata: WorkflowMetadata;
  /** @minItems 1 */
  nodes: WorkflowNode[];
  /** @minItems 0 */
  edges: WorkflowEdge[];
  /** Workflow-level tags. */
  tags?: string[];
}
