/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

/**
 * Execution role of the node.
 */
export type WorkflowNodeRole = typeof WorkflowNodeRole[keyof typeof WorkflowNodeRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkflowNodeRole = {
  node: 'node',
  container: 'container',
  middleware: 'middleware',
} as const;
