/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

export type WorkerPackagesItemStatus = typeof WorkerPackagesItemStatus[keyof typeof WorkerPackagesItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkerPackagesItemStatus = {
  installed: 'installed',
  installing: 'installing',
  uninstalling: 'uninstalling',
  removed: 'removed',
  failed: 'failed',
  unknown: 'unknown',
} as const;
