/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */
import type { WorkerCommandOneOf } from './workerCommandOneOf';
import type { WorkerCommandOneOfTwo } from './workerCommandOneOfTwo';
import type { WorkerCommandOneOfThree } from './workerCommandOneOfThree';
import type { WorkerCommandOneOfFour } from './workerCommandOneOfFour';

export type WorkerCommand = WorkerCommandOneOf | WorkerCommandOneOfTwo | WorkerCommandOneOfThree | WorkerCommandOneOfFour;
