/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */
import type { WorkerPackageSseEventStatus } from './workerPackageSseEventStatus';

export interface WorkerPackageSseEvent {
  kind: 'worker.package';
  workerId: string;
  package: string;
  /** @nullable */
  version?: string | null;
  status: WorkerPackageSseEventStatus;
  /** @nullable */
  message?: string | null;
}
