/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

export interface WorkflowPackageCloneRequest {
  /** Explicit version id to clone; defaults to the latest. */
  versionId?: string;
  /** Version string to clone when versionId is omitted. */
  version?: string;
  /** Optional override for the cloned workflow name. */
  workflowName?: string;
}
