/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

export interface WorkflowPreview {
  /**
   * Base64-encoded preview of the workflow canvas.
   * @nullable
   */
  previewImage?: string | null;
}
