/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduler Public API (v1)
 * OpenAPI spec version: 1.3.0
 */

/**
 * Default results payload seeded from the manifest schema.
 */
export type WorkflowMiddlewareResults = { [key: string]: unknown };
