# coding: utf-8

"""
    AstraFlow Hub API

    Public hub API for discovering packages and workflows.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hub_api.models.visibility import Visibility
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PackageVersionDetail(BaseModel):
    """
    PackageVersionDetail
    """ # noqa: E501
    name: StrictStr
    version: StrictStr
    description: Optional[StrictStr] = None
    readme: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    dist_tags: Optional[Dict[str, StrictStr]] = Field(default=None, alias="distTags")
    archive_sha256: Optional[StrictStr] = Field(default=None, alias="archiveSha256")
    archive_size_bytes: Optional[StrictInt] = Field(default=None, alias="archiveSizeBytes")
    owner_id: Optional[StrictStr] = Field(default=None, alias="ownerId")
    owner_name: Optional[StrictStr] = Field(default=None, alias="ownerName")
    visibility: Optional[Visibility] = None
    published_at: Optional[datetime] = Field(default=None, alias="publishedAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    __properties: ClassVar[List[str]] = ["name", "version", "description", "readme", "tags", "distTags", "archiveSha256", "archiveSizeBytes", "ownerId", "ownerName", "visibility", "publishedAt", "updatedAt"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PackageVersionDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PackageVersionDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "version": obj.get("version"),
            "description": obj.get("description"),
            "readme": obj.get("readme"),
            "tags": obj.get("tags"),
            "distTags": obj.get("distTags"),
            "archiveSha256": obj.get("archiveSha256"),
            "archiveSizeBytes": obj.get("archiveSizeBytes"),
            "ownerId": obj.get("ownerId"),
            "ownerName": obj.get("ownerName"),
            "visibility": obj.get("visibility"),
            "publishedAt": obj.get("publishedAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


