# coding: utf-8

"""
    AstraFlow Hub API

    Public hub API for discovering packages and workflows.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hub_api.models.package_dependency import PackageDependency
from hub_api.models.visibility import Visibility
from hub_api.models.workflow_definition import WorkflowDefinition
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WorkflowPublishRequest(BaseModel):
    """
    WorkflowPublishRequest
    """ # noqa: E501
    workflow_id: Optional[StrictStr] = Field(default=None, alias="workflowId")
    name: StrictStr
    version: StrictStr
    summary: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    visibility: Optional[Visibility] = None
    preview_image: Optional[StrictStr] = Field(default=None, alias="previewImage")
    dependencies: Optional[List[PackageDependency]] = None
    definition: WorkflowDefinition
    __properties: ClassVar[List[str]] = ["workflowId", "name", "version", "summary", "description", "tags", "visibility", "previewImage", "dependencies", "definition"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WorkflowPublishRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in dependencies (list)
        _items = []
        if self.dependencies:
            for _item in self.dependencies:
                if _item:
                    _items.append(_item.to_dict())
            _dict['dependencies'] = _items
        # override the default output from pydantic by calling `to_dict()` of definition
        if self.definition:
            _dict['definition'] = self.definition.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WorkflowPublishRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workflowId": obj.get("workflowId"),
            "name": obj.get("name"),
            "version": obj.get("version"),
            "summary": obj.get("summary"),
            "description": obj.get("description"),
            "tags": obj.get("tags"),
            "visibility": obj.get("visibility"),
            "previewImage": obj.get("previewImage"),
            "dependencies": [PackageDependency.from_dict(_item) for _item in obj.get("dependencies")] if obj.get("dependencies") is not None else None,
            "definition": WorkflowDefinition.from_dict(obj.get("definition")) if obj.get("definition") is not None else None
        })
        return _obj


