# coding: utf-8

"""
    AstraFlow Hub API

    Public hub API for discovering packages and workflows.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from hub_api.models.workflow_edge import WorkflowEdge
from hub_api.models.workflow_metadata import WorkflowMetadata
from hub_api.models.workflow_node import WorkflowNode
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WorkflowDefinition(BaseModel):
    """
    WorkflowDefinition
    """ # noqa: E501
    id: StrictStr
    schema_version: Annotated[str, Field(strict=True)] = Field(alias="schemaVersion")
    metadata: WorkflowMetadata
    nodes: Annotated[List[WorkflowNode], Field(min_length=1)]
    edges: List[WorkflowEdge]
    tags: Optional[List[StrictStr]] = None
    preview_image: Optional[StrictStr] = Field(default=None, alias="previewImage")
    subgraphs: Optional[List[WorkflowSubgraph]] = None
    __properties: ClassVar[List[str]] = ["id", "schemaVersion", "metadata", "nodes", "edges", "tags", "previewImage", "subgraphs"]

    @field_validator('schema_version')
    def schema_version_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[0-9]{4}-[0-9]{2}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WorkflowDefinition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in nodes (list)
        _items = []
        if self.nodes:
            for _item in self.nodes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['nodes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in edges (list)
        _items = []
        if self.edges:
            for _item in self.edges:
                if _item:
                    _items.append(_item.to_dict())
            _dict['edges'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in subgraphs (list)
        _items = []
        if self.subgraphs:
            for _item in self.subgraphs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['subgraphs'] = _items
        # set to None if preview_image (nullable) is None
        # and model_fields_set contains the field
        if self.preview_image is None and "preview_image" in self.model_fields_set:
            _dict['previewImage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WorkflowDefinition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "schemaVersion": obj.get("schemaVersion"),
            "metadata": WorkflowMetadata.from_dict(obj.get("metadata")) if obj.get("metadata") is not None else None,
            "nodes": [WorkflowNode.from_dict(_item) for _item in obj.get("nodes")] if obj.get("nodes") is not None else None,
            "edges": [WorkflowEdge.from_dict(_item) for _item in obj.get("edges")] if obj.get("edges") is not None else None,
            "tags": obj.get("tags"),
            "previewImage": obj.get("previewImage"),
            "subgraphs": [WorkflowSubgraph.from_dict(_item) for _item in obj.get("subgraphs")] if obj.get("subgraphs") is not None else None
        })
        return _obj

from hub_api.models.workflow_subgraph import WorkflowSubgraph
# TODO: Rewrite to not use raise_errors
WorkflowDefinition.model_rebuild(raise_errors=False)

