"""drop resource_grants

Revision ID: de8693e59b50
Revises: e9a5eba53973
Create Date: 2025-12-25 09:02:19.202870

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8693e59b50'
down_revision = 'e9a5eba53973'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_grants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_grants',
    sa.Column('id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('package_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('package_version', sa.VARCHAR(length=64), nullable=True),
    sa.Column('resource_key', sa.VARCHAR(length=128), nullable=False),
    sa.Column('scope', sa.VARCHAR(length=32), nullable=False),
    sa.Column('workflow_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('actions', sa.TEXT(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=128), nullable=True),
    sa.Column('metadata', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

