# generated by datamodel-codegen:
#   filename:  feedback.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr


class FeedbackChannel(Enum):
    stdout = "stdout"
    stderr = "stderr"
    log = "log"
    llm = "llm"
    metric = "metric"
    custom = "custom"


class FeedbackChunk(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    channel: FeedbackChannel
    index: Optional[conint(ge=0)] = None
    mime_type: Optional[constr(min_length=1)] = None
    text: Optional[str] = None
    data_base64: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None


class FeedbackPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    run_id: constr(min_length=1)
    task_id: constr(min_length=1)
    stage: Optional[constr(min_length=1)] = None
    progress: Optional[confloat(ge=0, le=1)] = None
    message: Optional[str] = None
    chunks: Optional[list[FeedbackChunk]] = Field(
        default=None, description="Streaming feedback emitted by the adapter."
    )
    metrics: Optional[Dict[str, float]] = None
    metadata: Optional[Dict[str, Any]] = None
