# generated by datamodel-codegen:
#   filename:  ack.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, conint


class AckPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ok: Optional[bool] = None
    for_: Optional[str] = Field(None, alias='for')
    info: Optional[str] = None
    ack_seq: Optional[conint(ge=0)] = None
    ack_bitmap: Optional[conint(ge=0)] = None
    recv_window: Optional[conint(ge=1)] = None
