RunId:
  name: runId
  in: path
  required: true
  schema:
    type: string
WorkflowId:
  name: workflowId
  in: path
  required: true
  schema:
    type: string
WorkerId:
  name: workerName
  in: path
  required: true
  schema:
    type: string
WorkerConnected:
  name: connected
  in: query
  required: false
  schema:
    type: boolean
WorkerRegistered:
  name: registered
  in: query
  required: false
  schema:
    type: boolean
WorkerHealthy:
  name: healthy
  in: query
  required: false
  schema:
    type: boolean
WorkerPackageName:
  name: packageName
  in: query
  required: false
  schema:
    type: string
WorkerPackageVersion:
  name: packageVersion
  in: query
  required: false
  schema:
    type: string
WorkerPackageStatus:
  name: packageStatus
  in: query
  required: false
  schema:
    $ref: './schemas/index.yaml#/WorkerPackageStatus'
WorkerMaxHeartbeatAgeSeconds:
  name: maxHeartbeatAgeSeconds
  in: query
  required: false
  schema:
    type: number
    minimum: 0
WorkerMaxInflight:
  name: maxInflight
  in: query
  required: false
  schema:
    type: integer
    minimum: 0
WorkerMaxLatencyMs:
  name: maxLatencyMs
  in: query
  required: false
  schema:
    type: integer
    minimum: 0
IdempotencyKey:
  name: Idempotency-Key
  in: header
  required: false
  schema:
    type: string
    maxLength: 64
  description: Optional idempotency key for safe retries; if reused with a different body, return 409
PageLimit:
  name: limit
  in: query
  required: false
  schema:
    type: integer
    minimum: 1
    maximum: 200
    default: 50
PageCursor:
  name: cursor
  in: query
  required: false
  schema:
    type: string
LastEventID:
  name: Last-Event-ID
  in: header
  required: false
  schema:
    type: string
  description: Resume SSE from a specific monotonic event id
ClientSessionId:
  name: clientSessionId
  in: query
  required: true
  schema:
    type: string
  description: Frontend-generated session identifier (UUID) used to route SSE events.
