# generated by datamodel-codegen:
#   filename:  exec.next.request.schema.json

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class ExecMiddlewareNextRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    requestId: constr(min_length=1)
    runId: constr(min_length=1)
    nodeId: constr(min_length=1)
    middlewareId: constr(min_length=1)
    chainIndex: Optional[conint(ge=0)] = None
    hostCtx: Optional[Dict[str, Any]] = Field(
        None, description='Host node context forwarded to the next middleware.'
    )
    middlewareCtx: Optional[Dict[str, Any]] = Field(
        None, description='Middleware-specific context for the next stage.'
    )
    payload: Optional[Dict[str, Any]] = Field(
        None, description='Adapter-emitted payload to pass to the next middleware/host.'
    )
    timeoutMs: Optional[conint(ge=1)] = Field(
        None, description='Optional local timeout hint for the waiter.'
    )
