# generated by datamodel-codegen:
#   filename:  session.accept.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr


class SessionAcceptPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: constr(min_length=1)
    session_token: constr(min_length=1)
    expires_at: Optional[AwareDatetime] = None
    resumed: Optional[bool] = None
    worker_instance_id: constr(min_length=1)
