# generated by datamodel-codegen:
#   filename:  session.resume.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, conint, constr


class SessionResumePayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: constr(min_length=1)
    session_token: constr(min_length=1)
    last_seen_seq: Optional[conint(ge=0)] = None
