# coding: utf-8

"""
    Scheduler Public API (v1)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class BindingScope(BaseModel):
    """
    Canonical representation of a binding prefix used to resolve nodes across workflows or subgraphs.
    """ # noqa: E501
    kind: Optional[StrictStr] = Field(default=None, description="local = default workflow, subgraph = inline subgraph alias chain.")
    subgraph_aliases: Optional[List[StrictStr]] = Field(default=None, description="Ordered list of inline subgraph aliases traversed to reach the node.", alias="subgraphAliases")
    node_id: Optional[UUID] = Field(default=None, description="Explicit node identifier within the resolved scope (used for '#nodeId' prefixes or workflow-level references).", alias="nodeId")
    prefix: Optional[StrictStr] = Field(default=None, description="Raw prefix string captured before parsing (mirrors UIBinding.prefix for auditing/backwards compatibility).")
    __properties: ClassVar[List[str]] = ["kind", "subgraphAliases", "nodeId", "prefix"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('local', 'subgraph',):
            raise ValueError("must be one of enum values ('local', 'subgraph')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BindingScope from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of BindingScope from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "kind": obj.get("kind"),
            "subgraphAliases": obj.get("subgraphAliases"),
            "nodeId": obj.get("nodeId"),
            "prefix": obj.get("prefix")
        })
        return _obj


