# coding: utf-8

"""
    Scheduler Public API (v1)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from scheduler_api.models.get_node200_response_runtimes_value import GetNode200ResponseRuntimesValue
from scheduler_api.models.get_node200_response_schema import GetNode200ResponseSchema
from scheduler_api.models.object import object
from scheduler_api.models.start_run_request_workflow_nodes_inner_ui import StartRunRequestWorkflowNodesInnerUi
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GetNode200Response(object):
    """
    GetNode200Response
    """ # noqa: E501
    type: StrictStr
    status: StrictStr
    category: StrictStr
    label: StrictStr
    description: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    runtimes: Optional[Dict[str, GetNode200ResponseRuntimesValue]] = Field(default=None, description="Implementation declarations per runtime namespace")
    var_schema: GetNode200ResponseSchema = Field(alias="schema")
    ui: Optional[StartRunRequestWorkflowNodesInnerUi] = None
    conditions: Optional[Dict[str, Any]] = Field(default=None, description="Reserved: gating rules / pre-run checks")
    extensions: Optional[Dict[str, Any]] = Field(default=None, description="Reserved: extensibility hooks")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Reserved: docs, example links, observability tags")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["type", "status", "category", "label", "description", "tags", "runtimes", "schema", "ui", "conditions", "extensions", "metadata"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('draft', 'published', 'deprecated',):
            raise ValueError("must be one of enum values ('draft', 'published', 'deprecated')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GetNode200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "additional_properties",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in runtimes (dict)
        _field_dict = {}
        if self.runtimes:
            for _key in self.runtimes:
                if self.runtimes[_key]:
                    _field_dict[_key] = self.runtimes[_key].to_dict()
            _dict['runtimes'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of var_schema
        if self.var_schema:
            _dict['schema'] = self.var_schema.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ui
        if self.ui:
            _dict['ui'] = self.ui.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GetNode200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "status": obj.get("status"),
            "category": obj.get("category"),
            "label": obj.get("label"),
            "description": obj.get("description"),
            "tags": obj.get("tags"),
            "runtimes": dict(
                (_k, GetNode200ResponseRuntimesValue.from_dict(_v))
                for _k, _v in obj.get("runtimes").items()
            )
            if obj.get("runtimes") is not None
            else None,
            "schema": GetNode200ResponseSchema.from_dict(obj.get("schema")) if obj.get("schema") is not None else None,
            "ui": StartRunRequestWorkflowNodesInnerUi.from_dict(obj.get("ui")) if obj.get("ui") is not None else None,
            "conditions": obj.get("conditions"),
            "extensions": obj.get("extensions"),
            "metadata": obj.get("metadata")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


