# coding: utf-8

"""
    Scheduler Public API (v1)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from scheduler_api.models.hub_visibility import HubVisibility
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class HubWorkflowDetail(BaseModel):
    """
    HubWorkflowDetail
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    summary: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    owner_id: Optional[StrictStr] = Field(default=None, alias="ownerId")
    owner_name: Optional[StrictStr] = Field(default=None, alias="ownerName")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    preview_image: Optional[StrictStr] = Field(default=None, alias="previewImage")
    visibility: Optional[HubVisibility] = None
    __properties: ClassVar[List[str]] = ["id", "name", "summary", "description", "tags", "ownerId", "ownerName", "updatedAt", "previewImage", "visibility"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HubWorkflowDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if summary (nullable) is None
        # and model_fields_set contains the field
        if self.summary is None and "summary" in self.model_fields_set:
            _dict['summary'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        # set to None if owner_id (nullable) is None
        # and model_fields_set contains the field
        if self.owner_id is None and "owner_id" in self.model_fields_set:
            _dict['ownerId'] = None

        # set to None if owner_name (nullable) is None
        # and model_fields_set contains the field
        if self.owner_name is None and "owner_name" in self.model_fields_set:
            _dict['ownerName'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updatedAt'] = None

        # set to None if preview_image (nullable) is None
        # and model_fields_set contains the field
        if self.preview_image is None and "preview_image" in self.model_fields_set:
            _dict['previewImage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of HubWorkflowDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "summary": obj.get("summary"),
            "description": obj.get("description"),
            "tags": obj.get("tags"),
            "ownerId": obj.get("ownerId"),
            "ownerName": obj.get("ownerName"),
            "updatedAt": obj.get("updatedAt"),
            "previewImage": obj.get("previewImage"),
            "visibility": obj.get("visibility")
        })
        return _obj


