# coding: utf-8

"""
    Scheduler Public API (v1)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from scheduler_api.models.manifest_node_schema import ManifestNodeSchema
from scheduler_api.models.manifest_node_ui import ManifestNodeUI
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ManifestNode(BaseModel):
    """
    ManifestNode
    """ # noqa: E501
    type: Annotated[str, Field(strict=True)]
    role: Optional[StrictStr] = Field(default=None, description="Execution role of the node.")
    status: StrictStr
    category: StrictStr
    label: StrictStr
    description: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    adapter: Annotated[str, Field(strict=True)]
    handler: Annotated[str, Field(strict=True)]
    config: Optional[Dict[str, Any]] = Field(default=None, description="Optional static configuration forwarded to the handler.")
    var_schema: ManifestNodeSchema = Field(alias="schema")
    ui: Optional[ManifestNodeUI] = None
    __properties: ClassVar[List[str]] = ["type", "role", "status", "category", "label", "description", "tags", "adapter", "handler", "config", "schema", "ui"]

    @field_validator('type')
    def type_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Za-z0-9_.-]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9_.-]+$/")
        return value

    @field_validator('role')
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('node', 'container', 'middleware',):
            raise ValueError("must be one of enum values ('node', 'container', 'middleware')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('draft', 'published', 'deprecated',):
            raise ValueError("must be one of enum values ('draft', 'published', 'deprecated')")
        return value

    @field_validator('adapter')
    def adapter_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Za-z0-9_.-]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9_.-]+$/")
        return value

    @field_validator('handler')
    def handler_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z_][A-Za-z0-9_]*$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ManifestNode from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_schema
        if self.var_schema:
            _dict['schema'] = self.var_schema.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ui
        if self.ui:
            _dict['ui'] = self.ui.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ManifestNode from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "role": obj.get("role"),
            "status": obj.get("status"),
            "category": obj.get("category"),
            "label": obj.get("label"),
            "description": obj.get("description"),
            "tags": obj.get("tags"),
            "adapter": obj.get("adapter"),
            "handler": obj.get("handler"),
            "config": obj.get("config"),
            "schema": ManifestNodeSchema.from_dict(obj.get("schema")) if obj.get("schema") is not None else None,
            "ui": ManifestNodeUI.from_dict(obj.get("ui")) if obj.get("ui") is not None else None
        })
        return _obj


