# coding: utf-8

"""
    Scheduler Public API (v1)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from scheduler_api.models.resource_visibility import ResourceVisibility
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Resource(BaseModel):
    """
    Resource
    """ # noqa: E501
    resource_id: StrictStr = Field(alias="resourceId")
    provider: StrictStr
    type: StrictStr
    filename: StrictStr
    owner_id: Optional[StrictStr] = Field(default=None, alias="ownerId")
    visibility: Optional[ResourceVisibility] = None
    mime_type: Optional[StrictStr] = Field(default=None, alias="mimeType")
    size_bytes: Annotated[int, Field(strict=True, ge=0)] = Field(alias="sizeBytes")
    sha256: Optional[StrictStr] = None
    created_at: datetime = Field(alias="createdAt")
    expires_at: Optional[datetime] = Field(default=None, alias="expiresAt")
    metadata: Optional[Dict[str, Any]] = None
    download_url: Optional[StrictStr] = Field(default=None, alias="downloadUrl")
    __properties: ClassVar[List[str]] = ["resourceId", "provider", "type", "filename", "ownerId", "visibility", "mimeType", "sizeBytes", "sha256", "createdAt", "expiresAt", "metadata", "downloadUrl"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Resource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if owner_id (nullable) is None
        # and model_fields_set contains the field
        if self.owner_id is None and "owner_id" in self.model_fields_set:
            _dict['ownerId'] = None

        # set to None if mime_type (nullable) is None
        # and model_fields_set contains the field
        if self.mime_type is None and "mime_type" in self.model_fields_set:
            _dict['mimeType'] = None

        # set to None if sha256 (nullable) is None
        # and model_fields_set contains the field
        if self.sha256 is None and "sha256" in self.model_fields_set:
            _dict['sha256'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expiresAt'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        # set to None if download_url (nullable) is None
        # and model_fields_set contains the field
        if self.download_url is None and "download_url" in self.model_fields_set:
            _dict['downloadUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Resource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "resourceId": obj.get("resourceId"),
            "provider": obj.get("provider"),
            "type": obj.get("type"),
            "filename": obj.get("filename"),
            "ownerId": obj.get("ownerId"),
            "visibility": obj.get("visibility"),
            "mimeType": obj.get("mimeType"),
            "sizeBytes": obj.get("sizeBytes"),
            "sha256": obj.get("sha256"),
            "createdAt": obj.get("createdAt"),
            "expiresAt": obj.get("expiresAt"),
            "metadata": obj.get("metadata"),
            "downloadUrl": obj.get("downloadUrl")
        })
        return _obj


