# coding: utf-8

"""
    Scheduler Public API (v1)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class ResourceGrantAction(str, Enum):
    """
    ResourceGrantAction
    """

    """
    allowed enum values
    """
    READ = 'read'
    WRITE = 'write'
    USE = 'use'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ResourceGrantAction from a JSON string"""
        return cls(json.loads(json_str))


