# coding: utf-8

"""
    Scheduler Public API (v1)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ResourceUploadSession(BaseModel):
    """
    ResourceUploadSession
    """ # noqa: E501
    upload_id: StrictStr = Field(alias="uploadId")
    filename: StrictStr
    size_bytes: Annotated[int, Field(strict=True, ge=0)] = Field(alias="sizeBytes")
    mime_type: Optional[StrictStr] = Field(default=None, alias="mimeType")
    sha256: Optional[StrictStr] = None
    chunk_size: Annotated[int, Field(strict=True, ge=1)] = Field(alias="chunkSize")
    uploaded_bytes: Annotated[int, Field(strict=True, ge=0)] = Field(alias="uploadedBytes")
    next_part: Annotated[int, Field(strict=True, ge=0)] = Field(alias="nextPart")
    total_parts: Annotated[int, Field(strict=True, ge=1)] = Field(alias="totalParts")
    completed_parts: Optional[List[Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, alias="completedParts")
    status: StrictStr
    resource_id: Optional[StrictStr] = Field(default=None, alias="resourceId")
    metadata: Optional[Dict[str, Any]] = None
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["uploadId", "filename", "sizeBytes", "mimeType", "sha256", "chunkSize", "uploadedBytes", "nextPart", "totalParts", "completedParts", "status", "resourceId", "metadata", "createdAt", "updatedAt"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('pending', 'completed', 'aborted',):
            raise ValueError("must be one of enum values ('pending', 'completed', 'aborted')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ResourceUploadSession from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if mime_type (nullable) is None
        # and model_fields_set contains the field
        if self.mime_type is None and "mime_type" in self.model_fields_set:
            _dict['mimeType'] = None

        # set to None if sha256 (nullable) is None
        # and model_fields_set contains the field
        if self.sha256 is None and "sha256" in self.model_fields_set:
            _dict['sha256'] = None

        # set to None if resource_id (nullable) is None
        # and model_fields_set contains the field
        if self.resource_id is None and "resource_id" in self.model_fields_set:
            _dict['resourceId'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ResourceUploadSession from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uploadId": obj.get("uploadId"),
            "filename": obj.get("filename"),
            "sizeBytes": obj.get("sizeBytes"),
            "mimeType": obj.get("mimeType"),
            "sha256": obj.get("sha256"),
            "chunkSize": obj.get("chunkSize"),
            "uploadedBytes": obj.get("uploadedBytes"),
            "nextPart": obj.get("nextPart"),
            "totalParts": obj.get("totalParts"),
            "completedParts": obj.get("completedParts"),
            "status": obj.get("status"),
            "resourceId": obj.get("resourceId"),
            "metadata": obj.get("metadata"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


