# coding: utf-8

"""
    Scheduler Public API (v1)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401



from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from scheduler_api.models.artifact_event import ArtifactEvent
from scheduler_api.models.command_ack_event import CommandAckEvent
from scheduler_api.models.command_error_event import CommandErrorEvent
from scheduler_api.models.node_error_event import NodeErrorEvent
from scheduler_api.models.node_result_delta_event import NodeResultDeltaEvent
from scheduler_api.models.node_result_snapshot_event import NodeResultSnapshotEvent
from scheduler_api.models.node_state_event import NodeStateEvent
from scheduler_api.models.node_status_event import NodeStatusEvent
from scheduler_api.models.run_metrics_event import RunMetricsEvent
from scheduler_api.models.run_snapshot_event import RunSnapshotEvent
from scheduler_api.models.run_status_event import RunStatusEvent
from scheduler_api.models.worker_heartbeat_event import WorkerHeartbeatEvent
from scheduler_api.models.worker_package_sse_event import WorkerPackageSseEvent
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

UIEVENTPAYLOAD_ONE_OF_SCHEMAS = ["ArtifactEvent", "CommandAckEvent", "CommandErrorEvent", "NodeErrorEvent", "NodeResultDeltaEvent", "NodeResultSnapshotEvent", "NodeStateEvent", "NodeStatusEvent", "RunMetricsEvent", "RunSnapshotEvent", "RunStatusEvent", "WorkerHeartbeatEvent", "WorkerPackageSseEvent"]

class UiEventPayload(BaseModel):
    """
    UiEventPayload
    """
    # data type: RunStatusEvent
    oneof_schema_1_validator: Optional[RunStatusEvent] = None
    # data type: RunSnapshotEvent
    oneof_schema_2_validator: Optional[RunSnapshotEvent] = None
    # data type: RunMetricsEvent
    oneof_schema_3_validator: Optional[RunMetricsEvent] = None
    # data type: NodeStateEvent
    oneof_schema_4_validator: Optional[NodeStateEvent] = None
    # data type: NodeStatusEvent
    oneof_schema_5_validator: Optional[NodeStatusEvent] = None
    # data type: NodeResultSnapshotEvent
    oneof_schema_6_validator: Optional[NodeResultSnapshotEvent] = None
    # data type: NodeResultDeltaEvent
    oneof_schema_7_validator: Optional[NodeResultDeltaEvent] = None
    # data type: NodeErrorEvent
    oneof_schema_8_validator: Optional[NodeErrorEvent] = None
    # data type: ArtifactEvent
    oneof_schema_9_validator: Optional[ArtifactEvent] = None
    # data type: CommandAckEvent
    oneof_schema_10_validator: Optional[CommandAckEvent] = None
    # data type: CommandErrorEvent
    oneof_schema_11_validator: Optional[CommandErrorEvent] = None
    # data type: WorkerHeartbeatEvent
    oneof_schema_12_validator: Optional[WorkerHeartbeatEvent] = None
    # data type: WorkerPackageSseEvent
    oneof_schema_13_validator: Optional[WorkerPackageSseEvent] = None
    actual_instance: Optional[Union[ArtifactEvent, CommandAckEvent, CommandErrorEvent, NodeErrorEvent, NodeResultDeltaEvent, NodeResultSnapshotEvent, NodeStateEvent, NodeStatusEvent, RunMetricsEvent, RunSnapshotEvent, RunStatusEvent, WorkerHeartbeatEvent, WorkerPackageSseEvent]] = None
    one_of_schemas: ClassVar[List[str]] = ["ArtifactEvent", "CommandAckEvent", "CommandErrorEvent", "NodeErrorEvent", "NodeResultDeltaEvent", "NodeResultSnapshotEvent", "NodeStateEvent", "NodeStatusEvent", "RunMetricsEvent", "RunSnapshotEvent", "RunStatusEvent", "WorkerHeartbeatEvent", "WorkerPackageSseEvent"]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = UiEventPayload.model_construct()
        error_messages = []
        match = 0
        # validate data type: RunStatusEvent
        if not isinstance(v, RunStatusEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RunStatusEvent`")
        else:
            match += 1
        # validate data type: RunSnapshotEvent
        if not isinstance(v, RunSnapshotEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RunSnapshotEvent`")
        else:
            match += 1
        # validate data type: RunMetricsEvent
        if not isinstance(v, RunMetricsEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RunMetricsEvent`")
        else:
            match += 1
        # validate data type: NodeStateEvent
        if not isinstance(v, NodeStateEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NodeStateEvent`")
        else:
            match += 1
        # validate data type: NodeStatusEvent
        if not isinstance(v, NodeStatusEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NodeStatusEvent`")
        else:
            match += 1
        # validate data type: NodeResultSnapshotEvent
        if not isinstance(v, NodeResultSnapshotEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NodeResultSnapshotEvent`")
        else:
            match += 1
        # validate data type: NodeResultDeltaEvent
        if not isinstance(v, NodeResultDeltaEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NodeResultDeltaEvent`")
        else:
            match += 1
        # validate data type: NodeErrorEvent
        if not isinstance(v, NodeErrorEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NodeErrorEvent`")
        else:
            match += 1
        # validate data type: ArtifactEvent
        if not isinstance(v, ArtifactEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ArtifactEvent`")
        else:
            match += 1
        # validate data type: CommandAckEvent
        if not isinstance(v, CommandAckEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CommandAckEvent`")
        else:
            match += 1
        # validate data type: CommandErrorEvent
        if not isinstance(v, CommandErrorEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CommandErrorEvent`")
        else:
            match += 1
        # validate data type: WorkerHeartbeatEvent
        if not isinstance(v, WorkerHeartbeatEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkerHeartbeatEvent`")
        else:
            match += 1
        # validate data type: WorkerPackageSseEvent
        if not isinstance(v, WorkerPackageSseEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkerPackageSseEvent`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in UiEventPayload with oneOf schemas: ArtifactEvent, CommandAckEvent, CommandErrorEvent, NodeErrorEvent, NodeResultDeltaEvent, NodeResultSnapshotEvent, NodeStateEvent, NodeStatusEvent, RunMetricsEvent, RunSnapshotEvent, RunStatusEvent, WorkerHeartbeatEvent, WorkerPackageSseEvent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in UiEventPayload with oneOf schemas: ArtifactEvent, CommandAckEvent, CommandErrorEvent, NodeErrorEvent, NodeResultDeltaEvent, NodeResultSnapshotEvent, NodeStateEvent, NodeStatusEvent, RunMetricsEvent, RunSnapshotEvent, RunStatusEvent, WorkerHeartbeatEvent, WorkerPackageSseEvent. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into RunStatusEvent
        try:
            instance.actual_instance = RunStatusEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RunSnapshotEvent
        try:
            instance.actual_instance = RunSnapshotEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RunMetricsEvent
        try:
            instance.actual_instance = RunMetricsEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NodeStateEvent
        try:
            instance.actual_instance = NodeStateEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NodeStatusEvent
        try:
            instance.actual_instance = NodeStatusEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NodeResultSnapshotEvent
        try:
            instance.actual_instance = NodeResultSnapshotEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NodeResultDeltaEvent
        try:
            instance.actual_instance = NodeResultDeltaEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NodeErrorEvent
        try:
            instance.actual_instance = NodeErrorEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ArtifactEvent
        try:
            instance.actual_instance = ArtifactEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CommandAckEvent
        try:
            instance.actual_instance = CommandAckEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CommandErrorEvent
        try:
            instance.actual_instance = CommandErrorEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkerHeartbeatEvent
        try:
            instance.actual_instance = WorkerHeartbeatEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkerPackageSseEvent
        try:
            instance.actual_instance = WorkerPackageSseEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into UiEventPayload with oneOf schemas: ArtifactEvent, CommandAckEvent, CommandErrorEvent, NodeErrorEvent, NodeResultDeltaEvent, NodeResultSnapshotEvent, NodeStateEvent, NodeStatusEvent, RunMetricsEvent, RunSnapshotEvent, RunStatusEvent, WorkerHeartbeatEvent, WorkerPackageSseEvent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into UiEventPayload with oneOf schemas: ArtifactEvent, CommandAckEvent, CommandErrorEvent, NodeErrorEvent, NodeResultDeltaEvent, NodeResultSnapshotEvent, NodeStateEvent, NodeStatusEvent, RunMetricsEvent, RunSnapshotEvent, RunStatusEvent, WorkerHeartbeatEvent, WorkerPackageSseEvent. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


