# coding: utf-8

"""
    Scheduler Public API (v1)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class UiEventType(str, Enum):
    """
    UiEventType
    """

    """
    allowed enum values
    """
    RUN_DOT_STATUS = 'run.status'
    RUN_DOT_SNAPSHOT = 'run.snapshot'
    RUN_DOT_METRICS = 'run.metrics'
    NODE_DOT_STATE = 'node.state'
    NODE_DOT_STATUS = 'node.status'
    NODE_DOT_RESULT_DOT_SNAPSHOT = 'node.result.snapshot'
    NODE_DOT_RESULT_DOT_DELTA = 'node.result.delta'
    NODE_DOT_ERROR = 'node.error'
    ARTIFACT_DOT_READY = 'artifact.ready'
    ARTIFACT_DOT_REMOVED = 'artifact.removed'
    COMMAND_DOT_ACK = 'command.ack'
    COMMAND_DOT_ERROR = 'command.error'
    WORKER_DOT_HEARTBEAT = 'worker.heartbeat'
    WORKER_DOT_PACKAGE = 'worker.package'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UiEventType from a JSON string"""
        return cls(json.loads(json_str))


