# coding: utf-8

"""
    Scheduler Public API (v1)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WorkflowPackageVersion(BaseModel):
    """
    WorkflowPackageVersion
    """ # noqa: E501
    id: StrictStr
    version: StrictStr
    changelog: Optional[StrictStr] = None
    published_at: datetime = Field(alias="publishedAt")
    publisher_id: Optional[StrictStr] = Field(default=None, alias="publisherId")
    preview_image: Optional[StrictStr] = Field(default=None, description="Base64-encoded preview of the workflow canvas for this version.", alias="previewImage")
    __properties: ClassVar[List[str]] = ["id", "version", "changelog", "publishedAt", "publisherId", "previewImage"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WorkflowPackageVersion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if changelog (nullable) is None
        # and model_fields_set contains the field
        if self.changelog is None and "changelog" in self.model_fields_set:
            _dict['changelog'] = None

        # set to None if publisher_id (nullable) is None
        # and model_fields_set contains the field
        if self.publisher_id is None and "publisher_id" in self.model_fields_set:
            _dict['publisherId'] = None

        # set to None if preview_image (nullable) is None
        # and model_fields_set contains the field
        if self.preview_image is None and "preview_image" in self.model_fields_set:
            _dict['previewImage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WorkflowPackageVersion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "version": obj.get("version"),
            "changelog": obj.get("changelog"),
            "publishedAt": obj.get("publishedAt"),
            "publisherId": obj.get("publisherId"),
            "previewImage": obj.get("previewImage")
        })
        return _obj


