# coding: utf-8

"""
    Scheduler Public API (v1)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from scheduler_api.models.worker_heartbeat_snapshot import WorkerHeartbeatSnapshot
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WorkerHeartbeatEvent(BaseModel):
    """
    WorkerHeartbeatEvent
    """ # noqa: E501
    kind: Optional[Any]
    worker_name: StrictStr = Field(alias="workerName")
    at: datetime
    queues: Optional[List[StrictStr]] = None
    instance_id: Optional[StrictStr] = Field(default=None, alias="instanceId")
    hostname: Optional[StrictStr] = None
    version: Optional[StrictStr] = None
    connected: Optional[StrictBool] = None
    registered: Optional[StrictBool] = None
    heartbeat: Optional[WorkerHeartbeatSnapshot] = None
    __properties: ClassVar[List[str]] = ["kind", "workerName", "at", "queues", "instanceId", "hostname", "version", "connected", "registered", "heartbeat"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WorkerHeartbeatEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of heartbeat
        if self.heartbeat:
            _dict['heartbeat'] = self.heartbeat.to_dict()
        # set to None if kind (nullable) is None
        # and model_fields_set contains the field
        if self.kind is None and "kind" in self.model_fields_set:
            _dict['kind'] = None

        # set to None if queues (nullable) is None
        # and model_fields_set contains the field
        if self.queues is None and "queues" in self.model_fields_set:
            _dict['queues'] = None

        # set to None if instance_id (nullable) is None
        # and model_fields_set contains the field
        if self.instance_id is None and "instance_id" in self.model_fields_set:
            _dict['instanceId'] = None

        # set to None if hostname (nullable) is None
        # and model_fields_set contains the field
        if self.hostname is None and "hostname" in self.model_fields_set:
            _dict['hostname'] = None

        # set to None if version (nullable) is None
        # and model_fields_set contains the field
        if self.version is None and "version" in self.model_fields_set:
            _dict['version'] = None

        # set to None if connected (nullable) is None
        # and model_fields_set contains the field
        if self.connected is None and "connected" in self.model_fields_set:
            _dict['connected'] = None

        # set to None if registered (nullable) is None
        # and model_fields_set contains the field
        if self.registered is None and "registered" in self.model_fields_set:
            _dict['registered'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WorkerHeartbeatEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "kind": obj.get("kind"),
            "workerName": obj.get("workerName"),
            "at": obj.get("at"),
            "queues": obj.get("queues"),
            "instanceId": obj.get("instanceId"),
            "hostname": obj.get("hostname"),
            "version": obj.get("version"),
            "connected": obj.get("connected"),
            "registered": obj.get("registered"),
            "heartbeat": WorkerHeartbeatSnapshot.from_dict(obj.get("heartbeat")) if obj.get("heartbeat") is not None else None
        })
        return _obj


