# coding: utf-8

"""
    Scheduler Public API (v1)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401



from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from scheduler_api.models.cmd_dispatch import CmdDispatch
from scheduler_api.models.command_ack import CommandAck
from scheduler_api.models.command_error import CommandError
from scheduler_api.models.node_error import NodeError
from scheduler_api.models.node_result import NodeResult
from scheduler_api.models.worker_heartbeat import WorkerHeartbeat
from scheduler_api.models.worker_package_event import WorkerPackageEvent
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

WSPAYLOAD_ONE_OF_SCHEMAS = ["CmdDispatch", "CommandAck", "CommandError", "NodeError", "NodeResult", "WorkerHeartbeat", "WorkerPackageEvent"]

class WsPayload(BaseModel):
    """
    WsPayload
    """
    # data type: CmdDispatch
    oneof_schema_1_validator: Optional[CmdDispatch] = None
    # data type: NodeResult
    oneof_schema_2_validator: Optional[NodeResult] = None
    # data type: NodeError
    oneof_schema_3_validator: Optional[NodeError] = None
    # data type: WorkerHeartbeat
    oneof_schema_4_validator: Optional[WorkerHeartbeat] = None
    # data type: WorkerPackageEvent
    oneof_schema_5_validator: Optional[WorkerPackageEvent] = None
    # data type: CommandAck
    oneof_schema_6_validator: Optional[CommandAck] = None
    # data type: CommandError
    oneof_schema_7_validator: Optional[CommandError] = None
    actual_instance: Optional[Union[CmdDispatch, CommandAck, CommandError, NodeError, NodeResult, WorkerHeartbeat, WorkerPackageEvent]] = None
    one_of_schemas: ClassVar[List[str]] = ["CmdDispatch", "CommandAck", "CommandError", "NodeError", "NodeResult", "WorkerHeartbeat", "WorkerPackageEvent"]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = WsPayload.model_construct()
        error_messages = []
        match = 0
        # validate data type: CmdDispatch
        if not isinstance(v, CmdDispatch):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CmdDispatch`")
        else:
            match += 1
        # validate data type: NodeResult
        if not isinstance(v, NodeResult):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NodeResult`")
        else:
            match += 1
        # validate data type: NodeError
        if not isinstance(v, NodeError):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NodeError`")
        else:
            match += 1
        # validate data type: WorkerHeartbeat
        if not isinstance(v, WorkerHeartbeat):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkerHeartbeat`")
        else:
            match += 1
        # validate data type: WorkerPackageEvent
        if not isinstance(v, WorkerPackageEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkerPackageEvent`")
        else:
            match += 1
        # validate data type: CommandAck
        if not isinstance(v, CommandAck):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CommandAck`")
        else:
            match += 1
        # validate data type: CommandError
        if not isinstance(v, CommandError):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CommandError`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in WsPayload with oneOf schemas: CmdDispatch, CommandAck, CommandError, NodeError, NodeResult, WorkerHeartbeat, WorkerPackageEvent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in WsPayload with oneOf schemas: CmdDispatch, CommandAck, CommandError, NodeError, NodeResult, WorkerHeartbeat, WorkerPackageEvent. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into CmdDispatch
        try:
            instance.actual_instance = CmdDispatch.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NodeResult
        try:
            instance.actual_instance = NodeResult.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NodeError
        try:
            instance.actual_instance = NodeError.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkerHeartbeat
        try:
            instance.actual_instance = WorkerHeartbeat.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkerPackageEvent
        try:
            instance.actual_instance = WorkerPackageEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CommandAck
        try:
            instance.actual_instance = CommandAck.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CommandError
        try:
            instance.actual_instance = CommandError.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into WsPayload with oneOf schemas: CmdDispatch, CommandAck, CommandError, NodeError, NodeResult, WorkerHeartbeat, WorkerPackageEvent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into WsPayload with oneOf schemas: CmdDispatch, CommandAck, CommandError, NodeError, NodeResult, WorkerHeartbeat, WorkerPackageEvent. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


