/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ArtifactEvent {
    'kind': ArtifactEventKindEnum;
    'runId': string;
    'nodeId'?: string | null;
    'artifactId': string;
    'url'?: string | null;
    'expiresAt'?: string | null;
    'sizeBytes'?: number | null;
}

export const ArtifactEventKindEnum = {
    ArtifactReady: 'artifact.ready',
    ArtifactRemoved: 'artifact.removed'
} as const;

export type ArtifactEventKindEnum = typeof ArtifactEventKindEnum[keyof typeof ArtifactEventKindEnum];


