/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Canonical representation of a binding prefix used to resolve nodes across workflows or subgraphs.
 */
export interface BindingScope {
    /**
     * local = default workflow, subgraph = inline subgraph alias chain.
     */
    'kind'?: BindingScopeKindEnum;
    /**
     * Ordered list of inline subgraph aliases traversed to reach the node.
     */
    'subgraphAliases'?: Array<string>;
    /**
     * Explicit node identifier within the resolved scope (used for \'#nodeId\' prefixes or workflow-level references).
     */
    'nodeId'?: string;
    /**
     * Raw prefix string captured before parsing (mirrors UIBinding.prefix for auditing/backwards compatibility).
     */
    'prefix'?: string;
}

export const BindingScopeKindEnum = {
    Local: 'local',
    Subgraph: 'subgraph'
} as const;

export type BindingScopeKindEnum = typeof BindingScopeKindEnum[keyof typeof BindingScopeKindEnum];


