/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const EventType = {
    WorkerHeartbeat: 'worker.heartbeat',
    WorkerStatus: 'worker.status',
    WorkerPackage: 'worker.package',
    RunDispatch: 'run.dispatch',
    RunResult: 'run.result',
    RunError: 'run.error',
    CommandAck: 'command.ack',
    CommandError: 'command.error'
} as const;

export type EventType = typeof EventType[keyof typeof EventType];



