/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HubPackageDependency } from './hub-package-dependency';
// May contain unused imports in some cases
// @ts-ignore
import type { HubVisibility } from './hub-visibility';

export interface HubWorkflowPublishRequest {
    'workflowId'?: string;
    'name': string;
    'version': string;
    'summary'?: string;
    'description'?: string;
    'tags'?: Array<string>;
    'visibility'?: HubVisibility;
    'previewImage'?: string;
    'dependencies'?: Array<HubPackageDependency>;
    'definition': { [key: string]: any; };
}



