/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ManifestPermissionRequirement {
    /**
     * Stable permission identifier used for grants.
     */
    'key': string;
    /**
     * Resource types covered by this permission (file, image, audio, video, kv, secret, etc.).
     */
    'types': Array<string>;
    /**
     * Optional storage providers this permission applies to.
     */
    'providers'?: Array<string>;
    /**
     * Allowed actions for the permission (read, write, use).
     */
    'actions'?: Array<string>;
    /**
     * Whether the permission must be granted before execution.
     */
    'required'?: boolean;
    /**
     * Human-readable explanation of why the permission is needed.
     */
    'description'?: string;
    /**
     * Additional permission metadata.
     */
    'metadata'?: { [key: string]: any; };
}

