/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BindingScope } from './binding-scope';

export interface ManifestBinding {
    'path': string;
    'mode'?: ManifestBindingModeEnum;
    /**
     * Optional textual prefix (e.g. \'@workflowA.subgraphB.#nodeY\') applied before resolving the JSON pointer.
     */
    'prefix'?: string;
    'scope'?: BindingScope;
}

export const ManifestBindingModeEnum = {
    Read: 'read',
    Write: 'write',
    TwoWay: 'two_way'
} as const;

export type ManifestBindingModeEnum = typeof ManifestBindingModeEnum[keyof typeof ManifestBindingModeEnum];


