/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ManifestAdapter } from './manifest-adapter';
// May contain unused imports in some cases
// @ts-ignore
import type { ManifestHooks } from './manifest-hooks';
// May contain unused imports in some cases
// @ts-ignore
import type { ManifestNode } from './manifest-node';
// May contain unused imports in some cases
// @ts-ignore
import type { ManifestPythonConfig } from './manifest-python-config';
// May contain unused imports in some cases
// @ts-ignore
import type { ManifestResource } from './manifest-resource';
// May contain unused imports in some cases
// @ts-ignore
import type { ManifestSignature } from './manifest-signature';

export interface PackageManifest {
    /**
     * Manifest schema version (semver).
     */
    'schemaVersion': string;
    /**
     * Package identifier (lowercase with dots/underscores).
     */
    'name': string;
    /**
     * Package version in semver format.
     */
    'version': string;
    /**
     * Short summary of the package.
     */
    'description': string;
    'adapters': Array<ManifestAdapter>;
    'python': ManifestPythonConfig;
    'nodes': Array<ManifestNode>;
    'resources'?: Array<ManifestResource>;
    'hooks'?: ManifestHooks;
    'signature'?: ManifestSignature;
}

