/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PackageHubMeta {
    'hubName': string;
    'hubVersion': string;
    'ownerId'?: string | null;
    'ownerName'?: string | null;
    'visibility'?: string | null;
    'publishedAt'?: string | null;
    'archiveSha256'?: string | null;
}

