/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PublishedPackageState } from './published-package-state';
// May contain unused imports in some cases
// @ts-ignore
import type { PublishedPackageVisibility } from './published-package-visibility';

export interface PublishedPackageRegistry {
    'name': string;
    'ownerId': string;
    'visibility': PublishedPackageVisibility;
    'state': PublishedPackageState;
    'createdAt': string;
    'updatedAt': string;
    'createdBy'?: string | null;
    'updatedBy'?: string | null;
}



