/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ResourceUploadSession {
    'uploadId': string;
    'filename': string;
    'sizeBytes': number;
    'mimeType'?: string | null;
    'sha256'?: string | null;
    'chunkSize': number;
    'uploadedBytes': number;
    'nextPart': number;
    'totalParts': number;
    'completedParts'?: Array<number>;
    'status': ResourceUploadSessionStatusEnum;
    'resourceId'?: string | null;
    'metadata'?: { [key: string]: any; } | null;
    'createdAt': string;
    'updatedAt': string;
}

export const ResourceUploadSessionStatusEnum = {
    Pending: 'pending',
    Completed: 'completed',
    Aborted: 'aborted'
} as const;

export type ResourceUploadSessionStatusEnum = typeof ResourceUploadSessionStatusEnum[keyof typeof ResourceUploadSessionStatusEnum];


