/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WorkerCommandOneOf2 {
    'type': WorkerCommandOneOf2TypeEnum;
    'name': string;
    'version'?: string;
    /**
     * Optional archive URL; defaults to the published package archive.
     */
    'url'?: string;
    /**
     * Optional SHA-256 checksum of the archive.
     */
    'sha256'?: string;
}

export const WorkerCommandOneOf2TypeEnum = {
    PkgInstall: 'pkg.install'
} as const;

export type WorkerCommandOneOf2TypeEnum = typeof WorkerCommandOneOf2TypeEnum[keyof typeof WorkerCommandOneOf2TypeEnum];


