/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WorkerPackagesInner {
    'name'?: string;
    'version'?: string;
    'status'?: WorkerPackagesInnerStatusEnum;
}

export const WorkerPackagesInnerStatusEnum = {
    Installed: 'installed',
    Installing: 'installing',
    Uninstalling: 'uninstalling',
    Removed: 'removed',
    Failed: 'failed',
    Unknown: 'unknown'
} as const;

export type WorkerPackagesInnerStatusEnum = typeof WorkerPackagesInnerStatusEnum[keyof typeof WorkerPackagesInnerStatusEnum];


