/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NodePackage } from './node-package';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeUI } from './node-ui';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowMiddleware } from './workflow-middleware';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowNodeLayout } from './workflow-node-layout';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowNodePosition } from './workflow-node-position';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowNodeSchema } from './workflow-node-schema';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowNodeState } from './workflow-node-state';

export interface WorkflowNode {
    /**
     * Node UUID
     */
    'id': string;
    /**
     * e.g. \"playwright.open_page\"
     */
    'type': string;
    /**
     * Execution role of the node.
     */
    'role'?: WorkflowNodeRoleEnum;
    'package': NodePackage;
    /**
     * Node lifecycle state.
     */
    'status': WorkflowNodeStatusEnum;
    /**
     * Group/category shown in the builder palette.
     */
    'category': string;
    'label': string;
    /**
     * Longer description of the node behaviour.
     */
    'description'?: string;
    /**
     * Keywords for search/filter.
     */
    'tags'?: Array<string>;
    'position': WorkflowNodePosition;
    'layout'?: WorkflowNodeLayout;
    /**
     * Default parameter payload seeded from the manifest schema.
     */
    'parameters'?: { [key: string]: any; };
    /**
     * Default results payload seeded from the manifest schema.
     */
    'results'?: { [key: string]: any; };
    'state'?: WorkflowNodeState;
    'schema'?: WorkflowNodeSchema;
    'ui'?: NodeUI;
    /**
     * Ordered list of middleware definitions attached to this node.
     */
    'middlewares'?: Array<WorkflowMiddleware>;
}

export const WorkflowNodeRoleEnum = {
    Node: 'node',
    Container: 'container',
    Middleware: 'middleware'
} as const;

export type WorkflowNodeRoleEnum = typeof WorkflowNodeRoleEnum[keyof typeof WorkflowNodeRoleEnum];
export const WorkflowNodeStatusEnum = {
    Draft: 'draft',
    Published: 'published',
    Deprecated: 'deprecated'
} as const;

export type WorkflowNodeStatusEnum = typeof WorkflowNodeStatusEnum[keyof typeof WorkflowNodeStatusEnum];


