/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkerCapabilities } from './worker-capabilities';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkerHeartbeatSnapshot } from './worker-heartbeat-snapshot';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkerPackage } from './worker-package';

export interface Worker {
    'id': string;
    'hostname'?: string;
    'lastHeartbeatAt': string;
    'queues': Array<string>;
    'packages'?: Array<WorkerPackage>;
    'meta'?: { [key: string]: any; };
    'connected'?: boolean | null;
    'registered'?: boolean | null;
    'tenant'?: string | null;
    'instanceId'?: string | null;
    'version'?: string | null;
    'capabilities'?: WorkerCapabilities;
    'payloadTypes'?: Array<string> | null;
    'heartbeat'?: WorkerHeartbeatSnapshot;
}

