/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler Public API (v1)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CmdDispatch } from './cmd-dispatch';
// May contain unused imports in some cases
// @ts-ignore
import type { CommandAck } from './command-ack';
// May contain unused imports in some cases
// @ts-ignore
import type { CommandError } from './command-error';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeError } from './node-error';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeErrorMetadata } from './node-error-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeResult } from './node-result';
// May contain unused imports in some cases
// @ts-ignore
import type { ResultError } from './result-error';
// May contain unused imports in some cases
// @ts-ignore
import type { TraceContext } from './trace-context';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkerHeartbeat } from './worker-heartbeat';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkerPackageEvent } from './worker-package-event';

/**
 * @type WsPayload
 */
export type WsPayload = CmdDispatch | CommandAck | CommandError | NodeError | NodeResult | WorkerHeartbeat | WorkerPackageEvent;


